version = 1

[[analyzers]]
name = "docker"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "21"

[[analyzers]]
name = "cxx"

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "react",
    "vue",
    "angularjs",
    "angular",
    "meteor",
    "ember"
  ]
  environment = [
    "nodejs",
    "browser",
    "jest",
    "mocha",
    "jquery",
    "mongo",
    "cypress",
    "vitest"
  ]

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "terraform"

[[analyzers]]
name = "swift"

[[analyzers]]
name = "sql"

[[analyzers]]
name = "scala"

[[analyzers]]
name = "ruby"

[[analyzers]]
name = "rust"

  [analyzers.meta]
  msrv = "stable"

[[analyzers]]
name = "php"

[[analyzers]]
name = "kotlin"

  [analyzers.meta]
  runtime_version = "19"
  language_version = "1.9"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/Arif-Ali-H00484788/Heriot-Watt-Coursework-and-Projects"
  dependencies_vendored = true

[[analyzers]]
name = "csharp"

[[analyzers]]
name = "ansible"